### ISSUE TITLE
Honour hard-tabs size

### ISSUE THREAD

**Issue by iHiD** [exercism/research_experiment_1#102]
Go uses tabs (not spaces) but I’d set each tab at a width of 4 spaces. There is no rule for it (there is everything from 2 to 8 space), but 4 seems like a good middle ground.

https://exercism-team.slack.com/archives/CQRLC00DT/p1581374862049600?thread_ts=1581368857.045100&cid=CQRLC00DT

**Comment by iHiD** [comment]
@kntsoriano @tehsphinx I notice that tab is currently set to the size of two spaces in the UI. Is this correct? If not, how do we correct it? Thanks :)

**Comment by kntsoriano** [comment]
I've submitted a PR, but it hasn't been approved yet. https://github.com/exercism/go/pull/1333

**Comment by iHiD** [comment]
@ErikSchierboom @kytrinyx Either of you got any ideas on this one?

**Comment by ErikSchierboom** [comment]
@iHiD Yep. I've responsed in that PR: https://github.com/exercism/go/pull/1333#issuecomment-606427327
