### ISSUE TITLE
Rust 1a Exercise has Incorrect "test_head" Test Case

### ISSUE THREAD

**Issue by coltontcrowe** [exercism/research_experiment_1#148]
The Rust 1a exercise has the goal of taking a slice of u8s and returning the largest segment of purely incrementing numbers contained within.

In the test_head test case, the slice [1, 2, 3, 5] is the input but the test's expected output is [1, 2, 3].  Given the premise, the input provided will yield [1, 2, 3, 5] as it continues to increase throughout.

Given that the function is named test_head, it would stand to reason that an input similar to [1, 2, 3, 2] should be used to give the expected output of [1, 2, 3].

**Comment by coltontcrowe** [comment]
I stand corrected.  It looks like this was addressed in #146 and I missed it.  Closing

**Comment by iHiD** [comment]
Thanks @coltontcrowe. I think it's caught a couple of people out! I've just merged https://github.com/exercism/research_experiment_1/pull/147 so it should be fixed once that propagates (cc @ErikSchierboom @coriolinus)
