### ISSUE TITLE
Common Lisp exercise with inconvenience when running tests and failing on submit

### ISSUE THREAD

**Issue by chwt** [exercism/research_experiment_1#155]
I have the issue that the Common Lisp task from the website (https://research.exercism.io/user_experiments/1) can not be successfully submitted.

Actual:
1. Have code ready and click "Run code".
2. Screen "Processing code" with spinner is shown but does not terminate. (After certain time user is asked for re-rerunning).

3. Click on "Cancel build" while spinner is shown.
4. Now the expected test result is shown. (When waiting longer on this page a "Code 512" will be shown instead of the test result).
5. Having correct result click on "Submit exercise" and rate difficulity.
6. After send rate "Oh dear, something's not working here ..." error screen is shown.

Expected:
ad 2. Build spinner is terminating and showing test result.
ad 6. Submit and rate is successful.

Browsers: Firefox 82.0.2, Vivaldi 3.4.2066.94

**Comment by iHiD** [comment]
@chwt Thanks. Is that any better now?

**Comment by chwt** [comment]
@iHiD Works now as expected, thank you.
