### ISSUE TITLE
x86-64 assembly function description

### ISSUE THREAD

**Issue by bergjohan** [exercism/research_experiment_1#35]
In x86-64 assembly, function parameters are passed in specific registers. If you are new to assembly, and don't know about [calling conventions](https://en.wikipedia.org/wiki/Calling_convention), it might be difficult to get started.

Maybe we should add a comment to the stub file, describing the function and its registers, to make it a bit easier.

Example:

```nasm
;
; int str_isalpha(const char *str);
;
; Parameters:
;   rdi - str
; Returns:
;   rax - a non-zero value if all characters in the string are alphabetic and there is at least one character, zero otherwise.
;
section .text
global str_isalpha
str_isalpha:
    ; Provide your implementation here
    ret
```

What do you think?

**Comment by bergjohan** [comment]
Or we could describe the registers in the README file, that might be better?

**Comment by ErikSchierboom** [comment]
I think it could work both ways, although I'd prefer it in the README I think.
