### ISSUE TITLE
Tweak markdown table layout to provide a bit more spacing?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/research_experiment_1#67]
In the README for Ruby 1 a I noticed that I had to squint a bit to work out the details of the markdown table. I suspect that this was just because I was unfamiliar with the exercise, but I think that giving it a bit more padding would help.

Here's what I was seeing:

<img width="259" alt="Screen Shot 2020-01-30 at 11 46 09 AM" src="https://user-images.githubusercontent.com/276834/73447705-35ad7f80-4357-11ea-9a27-9e5828f5702b.png">

**Comment by iHiD** [comment]
Thanks :)

**Comment by iHiD** [comment]
Now looks like this:

<img width="598" alt="Screenshot 2020-01-30 at 13 51 20" src="https://user-images.githubusercontent.com/286476/73455289-a52b6b00-4367-11ea-9510-32909381d44c.png">
<img width="583" alt="Screenshot 2020-01-30 at 13 51 27" src="https://user-images.githubusercontent.com/286476/73455291-a5c40180-4367-11ea-9e59-885c79fa7f86.png">
