### ISSUE TITLE
Editor on the JavaScript experiment doesn't render

### ISSUE THREAD

**Issue by kntsoriano** [exercism/research_experiment_1#71]
<img width="1431" alt="Screen Shot 2020-01-30 at 12 13 59 PM" src="https://user-images.githubusercontent.com/1901520/73448983-0cdab980-435a-11ea-9ec9-aa1becaee773.png">

**Comment by iHiD** [comment]
This is because JavaScript is missing a `.meta/config.json`.

**Comment by SleeplessByte** [comment]
(sorry!)

**Comment by ErikSchierboom** [comment]
@SleeplessByte I was working on fixing that, but could not get the test runner to run.

**Comment by SleeplessByte** [comment]
Still absolutely don't see the merit of the duplication of content in these files, nor their extra work and it's completely working against the grain.

See if this works: https://github.com/exercism/research_experiment_1/pull/94

**Comment by iHiD** [comment]
I'd they're actually just duplicates or reformatting then they'll be entirely scriptable, so no extra work, but it allows us to render the info in a much more user friendly way (try looking at one of the passing tests for the ruby one for example). If they're not duplicates, and so involve extra work, then they are be deduction adding extra info that isn't automatically deducable.

So for ruby, they'll be entirely scriptable, but make the user experience much better by their existence, so it'll be zero extra work for maintainers but much better for the user.

**Comment by kntsoriano** [comment]
Can we close this?
