### ISSUE TITLE
How people write <LANG> differently

### ISSUE THREAD

**Issue by kytrinyx** [exercism/research_experiment_1#77]
There is some variation in the READMEs:

>  This is Part 1 of our research into how people write x86-64 assembly differently.

vs

> This is Part 1 of our research into how people write Rust in varying styles.

Let's see if we can come up with consistent wording that everyone can agree on.

My suggestion:

_This is Part 1 of our research into differences in the ways in which people write LANGUAGE._

**Comment by ErikSchierboom** [comment]
I like the suggestion, although it does have "into ... in ... in ...", which are a lot of in-based words :) But I'm not sure if this is actually an issue.

**Comment by iHiD** [comment]
Thanks Erik!
