### ISSUE TITLE
Ruby 1-a test

### ISSUE THREAD

**Issue by kotp** [exercism/research_experiment_1#87]
In running through the exercise, it seems that there is improper value for a test:

```
Code Run:
cart = ShoppingCart.new
cart.add(:STARIC)
cart.add(:MEDNEW)
cart.add(:MEDNEW)
cart.items_list
Test Failure
Expected: "Newspaper, Rice"
  Actual: "Newspaper, Newspaper, Rice"
```

If I add two newspaper items to my list, I should expect two newspapers in my list.  My implementation achieves this, the test, I believe is incorrect.

cc: @pvcarrera

**Comment by kotp** [comment]
It looks like the tests purposely enforce unique list, but this seems counter-intuitive if it is a shopping list if there is no count provided.

**Comment by kytrinyx** [comment]
I don't know what the original intention of this was, but yesterday I updated the README to explicitly reflect the test expectations: https://github.com/exercism/research_experiment_1/pull/66

**Comment by pvcarrera** [comment]
I'm not sure if now is the right time to update the exercise but I can see how adding a counter to the `items_list` fits in the idea of a shopping cart. `items_list` could return something like: `"Newspaper: 2, Rice: 1"`

**Comment by kotp** [comment]
> I'm not sure if now is the right time to update the exercise but I can see how adding a counter to the `items_list` fits in the idea of a shopping cart. `items_list` could return something like: `"Newspaper: 2, Rice: 1"`

That is something the implementer can do, if we aren't forced to have unique items in the list... so that might be something for phase 2.  The time to modify them is here. ;)  It is live beta, (or live alpha, maybe).

**Comment by ErikSchierboom** [comment]
I was wondering what the status is of this issue?

**Comment by iHiD** [comment]
I'm happy to close it, as the README and tests are now consistent, and I like getting someone to use `uniq`. I understand @kotp's point, but `items_list` is ambiguous enough to me that it could go either way. I'd also happily see it changed to `item_names` or something, which is then less ambiguous in favour of having uniq.

**Comment by ErikSchierboom** [comment]
Alright. Let's close for now.
